### ISSUE TITLE
Add Privacy Policy Page

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#104]
Related to #85 create a privacy policy page that documents how we track usage analytics anonymously.

**Comment by nofurtherinformation** [comment]
Here's the termly generated example:

> PRIVACY NOTICE
> 
> Last updated May 24, 2022
> 
> 
> 
> This privacy notice for __________ ("Company," "we," "us," or "our"), describes how and why we might collect, store, use, and/or share ("process") your information when you use our services ("Services"), such as when you:
> Visit our website at https://decarbonizemystate.com/, or any website of ours that links to this privacy notice
> Engage with us in other related ways, including any sales, marketing, or events
> Questions or concerns? Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at __________.
> 
> 
> SUMMARY OF KEY POINTS
> 
> This summary provides key points from our privacy notice, but you can find out more details about any of these topics by clicking the link following each key point or by using our table of contents below to find the section you are looking for. You can also click [here](https://github.com/chihacknight/decarbonize-my-state/issues/104#toc) to go directly to our table of contents.
> 
> What personal information do we process? When you visit, use, or navigate our Services, we may process personal information depending on how you interact with __________ and the Services, the choices you make, and the products and features you use. Click [here](https://github.com/chihacknight/decarbonize-my-state/issues/104#personalinfo) to learn more.
> 
> Do we process any sensitive personal information? We do not process sensitive personal information.
> 
> Do we receive any information from third parties? We do not receive any information from third parties.
> 
> How do we process your information? We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so. Click [here](https://github.com/chihacknight/decarbonize-my-state/issues/104#infouse) to learn more.
> 
> In what situations and with which parties do we share personal information? We may share information in specific situations and with specific third parties. Click [here](https://github.com/chihacknight/decarbonize-my-state/issues/104#whoshare) to learn more.
> 
> How do we keep your information safe? We have organizational and technical processes and procedures in place to protect your personal information. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Click [here](https://github.com/chihacknight/decarbonize-my-state/issues/104#infosafe) to learn more.
> 
> What are your rights? Depending on w[here](https://github.com/chihacknight/decarbonize-my-state/issues/104#privacyrights) you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information. Click here to learn more.
> 
> How do I exercise my rights? The easiest way to exercise your rights is by filling out our data subject request form available here: __________, or by contacting us. We will consider and act upon any request in accordance with applicable data protection laws.
> 
> Want to learn more about what __________ does with any information we collect? Click [here](https://github.com/chihacknight/decarbonize-my-state/issues/104#toc) to review the notice in full.
> 
> 
> TABLE OF CONTENTS
> 
> [1. WHAT INFORMATION DO WE COLLECT?](https://github.com/chihacknight/decarbonize-my-state/issues/104#infocollect)
> [2. HOW DO WE PROCESS YOUR INFORMATION?](https://github.com/chihacknight/decarbonize-my-state/issues/104#infouse)
> [3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?](https://github.com/chihacknight/decarbonize-my-state/issues/104#whoshare)
> [4. HOW LONG DO WE KEEP YOUR INFORMATION?](https://github.com/chihacknight/decarbonize-my-state/issues/104#inforetain)
> [5. HOW DO WE KEEP YOUR INFORMATION SAFE?](https://github.com/chihacknight/decarbonize-my-state/issues/104#infosafe)
> [6. WHAT ARE YOUR PRIVACY RIGHTS?](https://github.com/chihacknight/decarbonize-my-state/issues/104#privacyrights)
> [7. CONTROLS FOR DO-NOT-TRACK FEATURES](https://github.com/chihacknight/decarbonize-my-state/issues/104#DNT)
> [8. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?](https://github.com/chihacknight/decarbonize-my-state/issues/104#caresidents)
> [9. DO WE MAKE UPDATES TO THIS NOTICE?](https://github.com/chihacknight/decarbonize-my-state/issues/104#policyupdates)
> [10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?](https://github.com/chihacknight/decarbonize-my-state/issues/104#contact)
> [11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?](https://github.com/chihacknight/decarbonize-my-state/issues/104#request)
> 
> 1. WHAT INFORMATION DO WE COLLECT?
> 
> Personal information you disclose to us
> 
> In Short: We collect personal information that you provide to us.
> 
> We collect personal information that you voluntarily provide to us when you express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.
> 
> Sensitive Information. We do not process sensitive information.
> 
> All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.
> 
> Information automatically collected
> 
> In Short: Some information — such as your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our Services.
> 
> We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes.
> 
> The information we collect includes:
> Log and Usage Data. Log and usage data is service-related, diagnostic, usage, and performance information our servers automatically collect when you access or use our Services and which we record in log files. Depending on how you interact with us, this log data may include your IP address, device information, browser type, and settings and information about your activity in the Services (such as the date/time stamps associated with your usage, pages and files viewed, searches, and other actions you take such as which features you use), device event information (such as system activity, error reports (sometimes called "crash dumps"), and hardware settings).
> Device Data. We collect device data such as information about your computer, phone, tablet, or other device you use to access the Services. Depending on the device used, this device data may include information such as your IP address (or proxy server), device and application identification numbers, location, browser type, hardware model, Internet service provider and/or mobile carrier, operating system, and system configuration information.
> Location Data. We collect location data such as information about your device's location, which can be either precise or imprecise. How much information we collect depends on the type and settings of the device you use to access the Services. For example, we may use GPS and other technologies to collect geolocation data that tells us your current location (based on your IP address). You can opt out of allowing us to collect this information either by refusing access to the information or by disabling your Location setting on your device. However, if you choose to opt out, you may not be able to use certain aspects of the Services.
> 2. HOW DO WE PROCESS YOUR INFORMATION?
> 
> In Short: We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.
> 
> We process your personal information for a variety of reasons, depending on how you interact with our Services, including:
> 
> 
> 
> 
> To identify usage trends. We may process information about how you use our Services to better understand how they are being used so we can improve them.
> 
> 3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?
> 
> In Short: We may share information in specific situations described in this section and/or with the following third parties.
> 
> Vendors, Consultants, and Other Third-Party Service Providers. We may share your data with third-party vendors, service providers, contractors, or agents ("third parties") who perform services for us or on our behalf and require access to such information to do that work. The third parties we may share personal information with are as follows:
> Web and Mobile Analytics
> Google Analytics
> 
> We also may need to share your personal information in the following situations:
> Business Transfers. We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
> 
> 4. HOW LONG DO WE KEEP YOUR INFORMATION?
> 
> In Short: We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law.
> 
> We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than 90 days.
> 
> When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.
> 
> 5. HOW DO WE KEEP YOUR INFORMATION SAFE?
> 
> In Short: We aim to protect your personal information through a system of organizational and technical security measures.
> 
> We have implemented appropriate and reasonable technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.
> 
> 6. WHAT ARE YOUR PRIVACY RIGHTS?
> 
> In Short:  You may review, change, or terminate your account at any time.
>  
> If you are located in the EEA or UK and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm.
> 
> If you are located in Switzerland, the contact details for the data protection authorities are available here: https://www.edoeb.admin.ch/edoeb/en/home.html.
> 
> Withdrawing your consent: If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us by using the contact details provided in the section "[HOW CAN YOU CONTACT US ABOUT THIS NOTICE?](https://github.com/chihacknight/decarbonize-my-state/issues/104#contact)" below.
> 
> However, please note that this will not affect the lawfulness of the processing before its withdrawal, nor when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.
> 
> 7. CONTROLS FOR DO-NOT-TRACK FEATURES
> 
> Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track ("DNT") feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.
> 
> 8. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?
> 
> In Short: Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.
> 
> California Civil Code Section 1798.83, also known as the "Shine The Light" law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.
> 
> If you are under 18 years of age, reside in California, and have a registered account with Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g., backups, etc.).
> 
> 9. DO WE MAKE UPDATES TO THIS NOTICE?
> 
> In Short: Yes, we will update this notice as necessary to stay compliant with relevant laws.
> 
> We may update this privacy notice from time to time. The updated version will be indicated by an updated "Revised" date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.
> 
> 10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?
> 
> If you have questions or comments about this notice, you may email us at __________ or by post to:
> 
> __________
> __________
> __________
> 
> 11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?
> 
> Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please visit: __________.
> This privacy policy was created using Termly's [Privacy Policy Generator](https://termly.io/prod

ucts/privacy-policy-generator).

**Comment by vkoves** [comment]
Dylan confirmed he can take this on, let's make sure to link this in the footer and not the header

**Comment by vkoves** [comment]
I'm closing this - we collect nothing except Google Analytics, and have no forms. We also serve US customers.
