### ISSUE TITLE
Create Resources Page

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#106]
List links to pages that we've found over the course of building this website that aren't necessarily on the calls to action page.

- links to website / articles
- videos
- books

Google doc: https://docs.google.com/document/d/1ovl13s905bOHRTOBxfDPRVwLDW9l8gleKUDF-_qDooE/edit

**Comment by vkoves** [comment]
@derekeder - should we just tack this onto the about page?

**Comment by vkoves** [comment]
Also we should link [Electrify by Saul Griffith](https://mitpress.mit.edu/books/electrify)

**Comment by derekeder** [comment]
We are already linking to Electrify and a number of other resources, so i think we can close this.
