### ISSUE TITLE
Update Replacement Power Generating Progress Graph

### ISSUE THREAD

**Issue by hkier** [chihacknight/decarbonize-my-state#108]
We currently break out the replacement power generation by wind and solar.  However, we do not take in to account emerging technologies.  Furthermore, the current method allocates a specific replacement ratio between wind and solar.  It really does not matter how the carbon emitting plants are replaced, they just need to be replaced by a clean generating plant.

**Comment by vkoves** [comment]
Closing this based on our discussion tonight - we want to specifically highlight solar and wind
