### ISSUE TITLE
Meta Description is Missing

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#110]
The meta description is broken for the homepage and the state pages, as I can see via Duck Duck Go or Google:

![screenshot_20220602-170407](https://user-images.githubusercontent.com/3187531/171966474-4ecd03f4-987b-4e01-9343-2fa476aa0384.png)

We should make the meta description for the state page unique to the state

**Comment by herrerarobert** [comment]
Is this bug still present? I made a PR with a small change to get a netlify preview build, and the search engine results pages appear to be dynamic by state when tested on https://metatags.io/ Here is a screenshot: 
![image](https://user-images.githubusercontent.com/27985352/173725582-e74cf603-a7e6-41cd-b103-ccebdd6bb98a.png)

**Comment by vkoves** [comment]
@herrerarobert - interesting, it looks like the _homepage_ is missing a description, but state pages already have it. If you just fix the homepage then, that should be fine!

| Homepage | State Page |
| ![Screenshot from 2022-06-15 12-04-52](https://user-images.githubusercontent.com/3187531/173884946-e4e1b13a-c193-4eac-9124-d0334bc7cdde.png) | ![Screenshot from 2022-06-15 12-05-00](https://user-images.githubusercontent.com/3187531/173884960-8d61d51b-6f9b-4489-96d3-4a671b3be4c0.png) |
