### ISSUE TITLE
decarbonizemystate.com Not Redirecting To decarbmystate.com

### ISSUE THREAD

**Issue by SuragNuthulapaty** [chihacknight/decarbonize-my-state#136]
![Screen Shot 2022-08-02 at 8 32 24 PM](https://user-images.githubusercontent.com/77648585/182504950-3512be2e-bf26-444a-a890-a53cf503d712.png)

make it so that decarbonizemysate.com redirects to decarbmystate.com

**Comment by derekeder** [comment]
I set up a URL redirect for decarbonizemystate.com => decarbmystate.com

**Comment by vkoves** [comment]
@derekeder - still not working (confirmed with multiple people) 😢

**Comment by derekeder** [comment]
this is done.

http://decarbonizemystate.com redirects to https://decarbmystate.com

However, http**s**://decarbonizemystate.com does not, because we do not have an SSL cert for that domain anymore
