### ISSUE TITLE
On State Details List Number of Wind Turbines and Acres/Football Fields of Solar to Build

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#142]
So on top of say we need to add 300 MWs of solar and 400 MWs of wind, we should say we this equivalent to building ~500 wind 20 foot turbines and 12 football fields of solar.

We should also make sure to asterisk this and state that every state has different weather, so in Arizona you would need less solar than in say upstate Vermont

**Comment by herrerarobert** [comment]
I found this government source which states that newly installed wind turbines can generate 843kWh of power per month. 

https://www.usgs.gov/faqs/how-many-homes-can-average-wind-turbine-power
