### ISSUE TITLE
Add Prettier (via ESLint)

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#147]
Let's make sure to add it and apply it to the whole codebase. Be warned, that PR will have merge conflicts anyttime people merge work so you should coordinate to get a quick review.

**Comment by SuragNuthulapaty** [comment]
@vkoves I was just checking, there is already prettier in the project and the `yarn format` command runs it for everything. Do I need to do anything then?

**Comment by vkoves** [comment]
@SuragNuthulapaty - interesting. Then I think you could make a PR running it for all files, and then add it to CI by adding it to the test command. I think the issue is CI doesn't fail if prettier has problems, so nobody knew to run it. It should also be added to the README.

**Comment by vkoves** [comment]
@SuragNuthulapaty - one other thing I noticed actually, it seems prettier may conflict with ESLint right now, at least just on semicolons. If just removing that from Prettier lets them play nice, that should be fine, but we may need to integrate PRettier into ESLint
