### ISSUE TITLE
Fix bugs on state page

### ISSUE THREAD

**Issue by jpvelez** [chihacknight/decarbonize-my-state#148]
1. Duplicate image: The water heat pump and stove are showing up twice on mobile view

<img src="https://user-images.githubusercontent.com/533641/186514353-6e7a16ec-de3e-478a-882b-28c08ab1054d.jpg" width="250">

2. Text mismatch: The text here is two difference sizes

<img src="https://user-images.githubusercontent.com/533641/186514340-3441f550-0685-4d08-9dd2-e90541b94dd4.png" width="250">

<img src="https://user-images.githubusercontent.com/533641/186514341-a2efcd63-f1c8-4f26-a348-6be9ee8a9853.png" width="250">

3. Language should be consistent: MW, not megawatts or Megawatts. And actually, we can shorten the language, since it's wall of text RN: "In all, we'll need to build 12GW or wind and 11GW of solar.<br><br> That means building TKMW of wind turbines and TKMW of solar panels every year."

<img src="https://user-images.githubusercontent.com/533641/186514266-4480f176-3c0e-447a-8ec3-66cb7cbdb0c4.jpg" width="250">

4. Spacing issue:

<img src="https://user-images.githubusercontent.com/533641/186514288-277e2bce-8957-4d99-b593-fedb26b46647.jpg" width="250">

**Comment by vkoves** [comment]
@derekeder - I'd love your thoughts on Juan's suggestion of moving to MW everywhere. We only use it right now on the power plant tiles (which are supplementary info) so my thought is to move to Megawatts everywhere. It's clearer and less technical than using MW.

**Comment by derekeder** [comment]
I agree we should be consistent. MW is shorter, but we are aiming for an audience that is new to these concepts. I think we should either:

1. Use "Megawatts" everywhere, or
2. Use "Megawatts (MW)" the first time, and then MW for all others after on the same page
