### ISSUE TITLE
Suggested tweaks to picture on state page

### ISSUE THREAD

**Issue by jpvelez** [chihacknight/decarbonize-my-state#149]
1. The following picture are very nice, and I think we could make them like 20-30% bigger so they catch the eye more. They don't have to be so big that they take up the whole page.
![File (2)](https://user-images.githubusercontent.com/533641/186514963-3a2a54db-d0b9-476e-9130-41fa427433f5.jpg)
![File (3)](https://user-images.githubusercontent.com/533641/186514988-74ee43f6-c1b2-49a6-b515-1caefecf698a.jpg)

2. Likewise, we should maybe stack these-only in mobile view-so that they're bigger. We don't have to make them so big that they fill up the page, and we can have the medium duty vehicle point the other direction from the other two, for visual variety. (And of course, we'd want to make sure the section with clean vehicles matched the orientations here.)
![File (1)](https://user-images.githubusercontent.com/533641/186515028-b37bfb86-b4bc-480b-8014-e387dd183e27.jpg)

**Comment by vkoves** [comment]
@derekeder - can you weigh in on this

**Comment by derekeder** [comment]
i think they're fine for now. we can close this
