### ISSUE TITLE
Create County Maps of Solar & Wind Deployments

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#155]
Derek mentioned this on the call tonight related to someone else's needs, to help combat laws that block solar and wind deployments in certain counties.

The EPA or EIA may have the data we need.

**Comment by SuragNuthulapaty** [comment]
I found a table with wind turbine data, it has both state and county. It is in the file titled "uswtdb_v5_1_20220729.csv" in the link below

https://www.sciencebase.gov/catalog/item/6001e327d34e592d8671fae0

**Comment by derekeder** [comment]
Some additional details on the request from Illinois Clean Jobs Coalition:

> It would be very helpful to have a statewide renewables map showing where solar and wind projects are deployed. Visuals would help to make the case to counties, as some counties in IL are anti-wind (likely from astroturf groups) and are restricting development. The state has known targets, so we could show a progress meter and break it out by region. 
> Also, many proposed projects are stuck in the queue awaiting approval. Calling these out would be very helpful. We can get connected to a renewables experts to learn more about this. Renewable energy credits (RECS) ties back to funding and budget.

**Comment by vkoves** [comment]
Derek, me, and Juan are having a call with an org Thursday to talk about solar info for Illinois

**Comment by derekeder** [comment]
For this to be useful for the ICJC folks, the source data needs to be updated at least quarterly. So far, I do not believe a national data source exists with this frequency.

For now, we are going to make a one-off map for IL based on this data from the Illinois Power Agency: https://illinoisabp.com/project-application-reports/ (Report no 3)
