### ISSUE TITLE
Link to YellowTin from Take Action Page

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#162]
I've been talking to the owner of Yellow Tin, a platform that allows people to financially plan for electrifying their homes & lifestyles.

What do folks think of adding a link on the take action page to their landing page? https://www.yellowtin.com/electrify-with-yellowtin/

More on what YellowTin is:

> YellowTin helps climate-leading organizations increase brand value and meet sustainability goals by empowering employee and customer stakeholders to transition to clean energy lifestyles.
>
> Fully customizable, our platform provides your stakeholders personalized insights based on local energy rates and incentives.
>
> They can plan and implement their clean electrification journey – from solar power and carbon-free electricity to electric vehicles and efficient home appliances – and opt-in to receive notifications when new incentives and technologies are introduced.

**Comment by vkoves** [comment]
@derekeder - should we still do this? Or do you want to discuss this at our next meeting?

**Comment by derekeder** [comment]
ah yes - lets discuss next meeting

**Comment by vkoves** [comment]
Derek confirmed we can just do this

**Comment by vkoves** [comment]
@derekeder - I realize this has been stale for a while, do we still want to do this? It looks like YellowTin has redesigned and is more corporate focused

**Comment by derekeder** [comment]
lets close it.
