### ISSUE TITLE
Setup Routes for Every Single US Power Plant

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#188]
Maybe a route like `/power-plants/:plant-slug`?

This can be hidden for now and log out the relevant data, then Viktor will come through and do a styling pass.

Relates to #184.

**Comment by derekeder** [comment]
Steps to take here:

- update `data/scripts/get_power_plants.py` to generate a unique URL `slug` for each power plant. Looks like we can use `state` and `plant_name` and [python-slugify](https://github.com/un33k/python-slugify)
- update `gatsby-node.js` to generate pages for each unique slug. Here's an example of how to do that with a `graphql` query: https://github.com/kyle-gracey/green-jobs/blob/main/gatsby-node.js
- create a component template called `/src/components/power-plant-detail.js` similar to `/src/components/state-detail.js`
- set up the `power-plant-detail.js` to do a `graphql` query to grab the power plant details based on the `slug` value and print out the data in a `console.log()` statement
- hand it over to @vkoves to do the front-end design!
