### ISSUE TITLE
add additional power plant fields

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#190]
With new power plant detail pages, we have over 300 fields we could bring in and make available for the page. 

Here's the fields we're currently pulling in:

* fossil_fuel_category
* state
* plant_name
* utility_name
* county
* capacity_mw

Here's the raw data: https://github.com/chihacknight/decarbonize-my-state/blob/main/data/raw/power_plants_and_communities.csv

@vkoves which of the new fields do you want to include?

Plant sequence number
eGRID Plant file sequence number
Data Year
state
plant_name
DOE/EIA ORIS plant or facility code
Plant transmission or distribution system owner name
Plant transmission or distribution system owner ID
utility_name
Utility ID
Plant-level sector
Balancing Authority Name
Balancing Authority Code
NERC region acronym
eGRID subregion acronym
eGRID subregion name
Plant associated ISO/RTO Territory 
Plant FIPS state code
Plant FIPS county code
county
Latitude
Longitude
Number of units
Number of generators
Plant primary fuel
fossil_fuel_category
Flag indicating if the plant burned or generated any amount of coal
Plant capacity factor
capacity_mw
Nonbaseload Factor
Biogas/ biomass plant adjustment flag
Combined heat and power (CHP) plant adjustment flag
CHP plant useful thermal output (MMBtu)
CHP plant power to heat ratio
CHP plant electric allocation factor
Plant pumped storage flag
Plant annual heat input from combustion (MMBtu)
Plant ozone season heat input from combustion (MMBtu)
Plant total annual heat input (MMBtu)
Plant total ozone season heat input (MMBtu)
Plant annual net generation (MWh)
Plant ozone season net generation (MWh)
Plant annual NOx emissions (tons)
Plant ozone season NOx emissions (tons)
Plant annual SO2 emissions (tons)
Plant annual CO2 emissions (tons)
Plant annual CH4 emissions (lbs)
Plant annual N2O emissions (lbs)
Plant annual CO2 equivalent emissions (tons)
Plant annual Hg emissions (lbs)
Plant annual NOx total output emission rate (lb/MWh)
Plant ozone season NOx total output emission rate (lb/MWh)
Plant annual SO2 total output emission rate (lb/MWh)
Plant annual CO2 total output emission rate (lb/MWh)
Plant annual CH4 total output emission rate (lb/MWh)
Plant annual N2O total output emission rate (lb/MWh)
Plant annual CO2 equivalent total output emission rate (lb/MWh)
Plant annual Hg total output emission rate (lb/MWh)
Plant annual NOx input emission rate (lb/MMBtu)
Plant ozone season NOx input emission rate (lb/MMBtu)
Plant annual SO2 input emission rate (lb/MMBtu)
Plant annual CO2 input emission rate (lb/MMBtu)
Plant annual CH4 input emission rate (lb/MMBtu)
Plant annual N2O input emission rate (lb/MMBtu)
Plant annual CO2 equivalent input emission rate (lb/MMBtu)
Plant annual Hg input emission rate (lb/MMBtu)
Plant annual NOx combustion output emission rate (lb/MWh)
Plant ozone season NOx combustion output emission rate (lb/MWh)
Plant annual SO2 combustion output emission rate (lb/MWh)
Plant annual CO2 combustion output emission rate (lb/MWh)
Plant annual CH4 combustion output emission rate (lb/MWh)
Plant annual N2O combustion output emission rate (lb/MWh)
Plant annual CO2 equivalent combustion output emission rate (lb/MWh)
Plant annual Hg combustion output emission rate (lb/MWh)
Plant unadjusted annual NOx emissions (tons)
Plant unadjusted ozone season NOx emissions (tons)
Plant unadjusted annual SO2 emissions (tons)
Plant unadjusted annual CO2 emissions (tons)
Plant unadjusted annual CH4 emissions (lbs)
Plant unadjusted annual N2O emissions (lbs)
Plant unadjusted annual Hg emissions (lbs)
Plant unadjusted annual heat input from combustion (MMBtu)
Plant unadjusted ozone season heat input from combustion (MMBtu)
Plant unadjusted total annual heat input (MMBtu)
Plant unadjusted total ozone season heat input (MMBtu)
Plant unadjusted annual NOx emissions source
Plant unadjusted ozone season NOx emissions source
Plant unadjusted annual SO2 emissions source
Plant unadjusted annual CO2 emissions source
Plant unadjusted annual CH4 emissions source
Plant unadjusted annual N2O emissions source
Plant unadjusted annual Hg emissions source
Plant unadjusted annual heat input source
Plant unadjusted ozone season heat input source
Plant annual NOx biomass emissions (tons)
Plant ozone season NOx biomass emissions (tons)
Plant annual SO2 biomass emissions (tons)
Plant annual CO2 biomass emissions (tons)
Plant annual CH4 biomass emissions (lbs)
Plant annual N2O biomass emissions (lbs)
Plant combustion heat input CHP adjustment value (MMBtu)
Plant combustion annual ozone season heat input CHP adjustment value (MMBtu)
Plant annual NOx emissions CHP adjustment value (tons)
Plant ozone season NOx emissions CHP adjustment value (tons)
Plant annual SO2 emissions CHP adjustment value (tons)
Plant annual CO2 emissions CHP adjustment value (tons)
Plant annual CH4 emissions CHP adjustment value (lbs)
Plant annual N2O emissions CHP adjustment value (lbs)
Plant nominal heat rate (Btu/kWh)
Plant annual coal net generation (MWh)
Plant annual oil net generation (MWh)
Plant annual gas net generation (MWh)
Plant annual nuclear net generation (MWh)
Plant annual hydro net generation (MWh)
Plant annual biomass net generation (MWh)
Plant annual wind net generation (MWh)
Plant annual solar net generation (MWh)
Plant annual geothermal net generation (MWh)
Plant annual other fossil net generation (MWh)
Plant annual other unknown/ purchased fuel net generation (MWh)
Plant annual total nonrenewables net generation (MWh)
Plant annual total renewables net generation (MWh)
Plant annual total nonhydro renewables net generation (MWh)
Plant annual total combustion net generation (MWh)
Plant annual total noncombustion net generation (MWh)
Plant coal generation percent (resource mix)
Plant oil generation percent (resource mix)
Plant gas generation percent (resource mix)
Plant nuclear generation percent (resource mix)
Plant hydro generation percent (resource mix)
Plant biomass generation percent (resource mix)
Plant wind generation percent (resource mix)
Plant solar generation percent (resource mix)
Plant geothermal generation percent (resource mix)
Plant other fossil generation percent (resource mix)
Plant other unknown / purchased fuel generation percent (resource mix)
Plant total nonrenewables generation percent (resource mix)
Plant total renewables generation percent (resource mix)
Plant total nonhydro renewables generation percent (resource mix)
Plant total combustion generation percent (resource mix)
Plant total noncombustion generation percent (resource mix)
CAMD Flag
CAMD Units
 2020 Plant total Heat Input (mmBtu) from CAMD 
 2020 Plant total CO2 mass (tons) from CAMD 
 2020 Plant total NOx mass (tons) from CAMD 
 2020 Plant total SO2 mass (tons) from CAMD 
 2020 Plant total Mercury mass (tons) from CAMD 
 Google Maps 
 total population (ACS2018) 
 Total Population for whom Poverty Status is Determined 
 Total Households 
 Total Population Age 25 up 
 Houses Built Pre 1960 
Buffer distance
State Abbreviation
State Name
EPA region number
State percentile for EJ Index for Particulate Matter (PM 2.5)
Regional percentile for EJ Index for Particulate Matter (PM 2.5)
National percentile for EJ Index for Particulate Matter (PM 2.5)
State percentile for EJ Index for Ozone
Regional percentile for EJ Index for Ozone
National percentile for EJ Index for Ozone
State percentile for EJ Index for NATA Diesel PM
Regional percentile for EJ Index for NATA Diesel PM
National percentile for EJ Index for NATA Diesel PM
State percentile for EJ Index for NATA Air Toxics Cancer Risk
Regional percentile for EJ Index for NATA Air Toxics Cancer Risk
National percentile for EJ Index for NATA Air Toxics Cancer Risk
State percentile for EJ Index for NATA Respiratory Hazard Index
Regional percentile for EJ Index for NATA Respiratory Hazard Index
National percentile for EJ Index for NATA Respiratory Hazard Index
State percentile for EJ Index for Traffic Proximity and Volume
Regional percentile for EJ Index for Traffic Proximity and Volume
National percentile for EJ Index for Traffic Proximity and Volume
State percentile for EJ Index for Lead Paint Indicator
Regional percentile for EJ Index for Lead Paint Indicator
National percentile for EJ Index for Lead Paint Indicator
State percentile for EJ Index for Superfund Proximity
Regional percentile for EJ Index for Superfund Proximity
National percentile for EJ Index for Superfund Proximity
State percentile for EJ Index for RMP Proximity
Regional percentile for EJ Index for RMP Proximity
National percentile for EJ Index for RMP Proximity
State percentile for EJ Index for Hazardous Waste Proximity
Regional percentile for EJ Index for Hazardous Waste Proximity
National percentile for EJ Index for Hazardous Waste Proximity
State percentile for EJ Index for Wastewater Discharge Indicator
Regional percentile for EJ Index for Wastewater Discharge Indicator
National percentile for EJ Index for Wastewater Discharge Indicator
Raw data for Particulate Matter (PM 2.5 in ug/m3)
State percentile for Particulate Matter (PM 2.5 in ug/m3)
Regional percentile for Particulate Matter (PM 2.5 in ug/m3)
National percentile for Particulate Matter (PM 2.5 in ug/m3)
State average for Particulate Matter (PM 2.5 in ug/m3)
Regional average for Particulate Matter (PM 2.5 in ug/m3)
National average for Particulate Matter (PM 2.5 in ug/m3)
Raw data for Ozone (ppb)
State percentile for Ozone (ppb)
Regional percentile for Ozone (ppb)
National percentile for Ozone (ppb)
State average for Ozone (ppb)
Regional average for Ozone (ppb)
National average for Ozone (ppb)
Raw data for NATA Diesel PM (ug/m3)
State percentile for NATA Diesel PM (ug/m3)
Regional percentile for NATA Diesel PM (ug/m3)
National percentile for NATA Diesel PM (ug/m3)
State average for NATA Diesel PM (ug/m3)
Regional average for NATA Diesel PM (ug/m3)
National average for NATA Diesel PM (ug/m3)
Raw data for NATA Air Toxics Cancer Risk (risk per MM)
State percentile for NATA Air Toxics Cancer Risk (risk per MM)
Regional percentile for NATA Air Toxics Cancer Risk (risk per MM)
National percentile for NATA Air Toxics Cancer Risk (risk per MM)
State average for NATA Air Toxics Cancer Risk (risk per MM)
Regional average for NATA Air Toxics Cancer Risk (risk per MM)
National average for NATA Air Toxics Cancer Risk (risk per MM)
Raw data for NATA Respiratory Hazard Index
State percentile for NATA Respiratory Hazard Index
Regional percentile for NATA Respiratory Hazard Index
National percentile for NATA Respiratory Hazard Index
State average for NATA Respiratory Hazard Index
Regional average for NATA Respiratory Hazard Index
National average for NATA Respiratory Hazard Index
Raw data for Traffic Proximity and Volume (daily traffic count/distance to road)
State percentile for Traffic Proximity and Volume (daily traffic count/distance to road)
Regional percentile for Traffic Proximity and Volume (daily traffic count/distance to road)
National percentile for Traffic Proximity and Volume (daily traffic count/distance to road)
State average for Traffic Proximity and Volume (daily traffic count/distance to road)
Regional average for Traffic Proximity and Volume (daily traffic count/distance to road)
National average for Traffic Proximity and Volume (daily traffic count/distance to road)
Raw data for Lead Paint Indicator (% pre-1960s housing)
State percentile for Lead Paint Indicator (% pre-1960s housing)
Regional percentile for Lead Paint Indicator (% pre-1960s housing)
National percentile for Lead Paint Indicator (% pre-1960s housing)
State average for Lead Paint Indicator (% pre-1960s housing)
Regional average for Lead Paint Indicator (% pre-1960s housing)
National average for Lead Paint Indicator (% pre-1960s housing)
Raw data for Superfund Proximity (site count/km distance)
State percentile for Superfund Proximity (site count/km distance)
Regional percentile for Superfund Proximity (site count/km distance)
National percentile for Superfund Proximity (site count/km distance)
State average for Superfund Proximity (site count/km distance)
Regional average for Superfund Proximity (site count/km distance)
National average for Superfund Proximity (site count/km distance)
Raw data for RMP Proximity (facility count/km distance)
State percentile for RMP Proximity (facility count/km distance)
Regional percentile for RMP Proximity (facility count/km distance)
National percentile for RMP Proximity (facility count/km distance)
State average for RMP Proximity (facility count/km distance)
Regional average for RMP Proximity (facility count/km distance)
National average for RMP Proximity (facility count/km distance)
Raw data for Hazardous Waste Proximity (facility count/km distance)
State percentile for Hazardous Waste Proximity (facility count/km distance)
Regional percentile for Hazardous Waste Proximity (facility count/km distance)
National percentile for Hazardous Waste Proximity (facility count/km distance)
State average for Hazardous Waste Proximity (facility count/km distance)
Regional average for Hazardous Waste Proximity (facility count/km distance)
National average for Hazardous Waste Proximity (facility count/km distance)
Raw data for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
State percentile for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
Regional percentile for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
National percentile for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
State average for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
Regional average for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
National average for Wastewater Discharge Indicators (toxicity-weighted concentration/m distance)
Raw data for Demographic Index
State percentile for Demographic Index
Regional percentile for Demographic Index
National percentile for Demographic Index
State average for Demographic Index
Regional average for Demographic Index
National average for Demographic Index
Raw data for People of Color Population
State percentile for People of Color Population
Regional percentile for People of Color Population
National percentile for People of Color Population
State average for People of Color Population
Regional average for People of Color Population
National average for People of Color Population
Raw data for Low Income Population
State percentile for Low Income Population
Regional percentile for Low Income Population
National percentile for Low Income Population
State average for Low Income Population
Regional average for Low Income Population
National average for Low Income Population
Raw data for Linguistically Isolated Population
State percentile for Linguistically Isolated Population
Regional percentile for Linguistically Isolated Population
National percentile for Linguistically Isolated Population
State average for Linguistically Isolated Population
Regional average for Linguistically Isolated Population
National average for Linguistically Isolated Population
Raw data for Population with Less Than High School Education
State percentile for Population with Less Than High School Education
Regional percentile for Population with Less Than High School Education
National percentile for Population with Less Than High School Education
State average for Population with Less Than High School Education
Regional average for Population with Less Than High School Education
National average for Population with Less Than High School Education
Raw data for Population under Age 5
State percentile for Population under Age 5
Regional percentile for Population under Age 5
National percentile for Population under Age 5
State average for Population under Age 5
Regional average for Population under Age 5
National average for Population under Age 5
Raw data for Population over Age 64
State percentile for Population over Age 64
Regional percentile for Population over Age 64
National percentile for Population over Age 64
State average for Population over Age 64
Regional average for Population over Age 64
National average for Population over Age 64
PM 2.5 Emssions (tons)
PM 2.5 Emission Rate (lb/MWh)
Mapped Fuel Type
Additional Number Data First
Additional Number Data Second
Additional Number Data Third
Additional Text Data First
Additional Text Data Second
Additional Text Data Third

**Comment by vkoves** [comment]
@derekeder - I think the annual pollution numbers for different pollutants would be good, but the main one is "Plant annual CO2 equivalent emissions (tons)", the "capacity_mw" and the "Plant annual net generation (MWh)". I trust your judgement on the location data, and if you could get it so say the first power plant on any state details page logs out this info that would make it easier for me to spot check if anything is missing.

We can also always tweak this later though, so I think as long as we get the core info I show in the designs to start, that'll be fine!

**Comment by derekeder** [comment]
Cool, so the fields to add are:

* Plant annual CO2 equivalent emissions (tons)
* Plant annual NOx emissions (tons)
* Plant annual SO2 emissions (tons)
* Plant annual CO2 emissions (tons)
* Plant annual CH4 emissions (lbs)
* Plant annual N2O emissions (lbs)
* Plant annual net generation (MWh)
* Latitude
* Longitude

@SuragNuthulapaty while you're editing `data/scripts/get_power_plants.py` could you add these fields to `cols_to_keep`?

**Comment by vkoves** [comment]
@derekeder - I'm now looking at this list more closely, and I think this can actually solve some ranking problems. I'm considering:

- Raw data for Particulate Matter (PM 2.5 in ug/m3)
- State percentile for Particulate Matter (PM 2.5 in ug/m3)
- National percentile for Particulate Matter (PM 2.5 in ug/m3)
- State average for Particulate Matter (PM 2.5 in ug/m3)
- National average for Particulate Matter (PM 2.5 in ug/m3)

There's also some really interesting socio-economic data, like "Raw data for People of Color Population", data on population over the age of 65, and more. I do think the raw pollution and power generation though doesn't have rankings, so I'll pull this into a new ticket and close this one.
