### ISSUE TITLE
Assemble Data Dictionary for all data sources used

### ISSUE THREAD

**Issue by swatland610** [chihacknight/decarbonize-my-state#24]
Starting with this [google sheet](https://docs.google.com/spreadsheets/d/1Ddb72w6Uu3tk0RR8Bl9XqXTrNpWllw99Cbm1UeyDk6w/edit#gid=0), let's organize all of our data sources into one shareable location. 
- Where is the source of this data? 
- What is it?
- How are we using it?
- Any links available for the data

**Comment by derekeder** [comment]
@swatland610 I've started documenting this in the About page draft: https://docs.google.com/document/d/1qXuioHvuRF28oBrKD_iPPiQRbiQw_A4kx3FU245e3go/edit#heading=h.1w2xoxatg5hj

**Comment by swatland610** [comment]
@derekeder yes! I'll try to get to it tomorrow morning. As well as my other issue I just need to wrap up

**Comment by vkoves** [comment]
@swatland610 - the about page now has all of the data sources, but now how we are using it, which I would have found helpful even making the slide deck. Would you be interested in adding that in, or should we assign that to someone else? I think after that we can close this issue.

**Comment by swatland610** [comment]
I agree with you! This is probably solved by the About page. I'll close out this issue.

**Comment by vkoves** [comment]
Closing in favor of #132, which cites sources in place

**Comment by swatland610** [comment]
Yeah let's just close this!
