### ISSUE TITLE
Create FAQ Page to Address Common Concerns

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#30]
Let's answer folks' most common questions about electrification. Some things that came up:

- Are induction stoves good?
- Are EVs really better than a gas car? What if I don't drive much?
- What about gas dryers?

**Note:** Saul Griffith's book has some good sections on this too

**Comment by vkoves** [comment]
Samantha is going to take this on

**Comment by sjegoodman** [comment]
https://www.rewiringamerica.org/electrify-home-guide
Lots of good stuff here

**Comment by sjegoodman** [comment]
Google Doc with lots of topics, some questions written out, bunch of Chicago/ComEd links:
https://docs.google.com/document/d/1bjZmh0gmBaPqcgG0EsrsxPnkSjtniM4b7pUQy8Cc8OM/edit?usp=sharing

**Comment by derekeder** [comment]
This is a great compilation of campaigns and tactics used by gas companies in New York to put up opposition to bills that reduce the amount of natural gas usage. Something to reference when thinking about the kinds of disinformation we will likely encounter: https://docs.google.com/document/d/1cTnGv_x5VEuXjFv75osbEcIRt9-hLBDRZOaFlm-vSi0/edit

**Comment by derekeder** [comment]
I'll plan to add some content to the FAQ in the next week

**Comment by derekeder** [comment]
I stubbed out some questions i think we should answer in 3 main categories: 

* Hesitation and skepticism about electrification (working title)
* Other proposals to fight climate change
* Things electrification doesn’t address

https://docs.google.com/document/d/1bjZmh0gmBaPqcgG0EsrsxPnkSjtniM4b7pUQy8Cc8OM/edit#

We can start researching and answering each one.

**Comment by hkier** [comment]
I do not have access to the google doc with the FAQ.  Can someone please add howardrkier@gmail.com?

**Comment by jmadans** [comment]
I added a answers to a couple of questions. IMHO I don't think we know enough to anticipate the questions and our users still have google. If we really want to usefully answer questions beyond the most core - say - three then let's just let people leave questions and I will answer them as we go.

I'm volunteering because I think we will get ZERO questions.

**Comment by vkoves** [comment]
Want to note we did get the "is an EV actually less carbon than a gas car" during our talk, so I think an FAQ could absolutely be worth it. I'm curious if other folks have seen or heard of questions related to the site.
