### ISSUE TITLE
Tweak Bar Chart Styling to Make Emissions Clearly Gone

### ISSUE THREAD

**Issue by jpvelez** [chihacknight/decarbonize-my-state#50]
could we make the bar look more like this as it is depleted?
so it’s clear that like... them emissions are gone

Like in [these slides](https://docs.google.com/presentation/d/1ShFq8tIScaU8MuIfJj30oAaBll3J4wfSEd_fv1FAGu8/edit#slide=id.g11f8e3f3150_0_21):

![Screenshot from 2022-04-13 19-51-04](https://user-images.githubusercontent.com/3187531/163292755-7b45a7c5-c18f-4122-8849-95db9fbe186f.png)

**Comment by derekeder** [comment]
we discussed and there are some challenges to accomplish this with `Recharts`. We're going to address this after the MVP

A few resources for reference:
* https://recharts.org/en-US/api/Cell
* https://recharts.org/en-US/api/ReferenceArea

**Comment by derekeder** [comment]
closing this for now
