### ISSUE TITLE
render power plants on state detail page

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#52]
Once #51 comes in, we will have access to 3 lists of power plants: coal, gas and oil.

Following the wireframes, we'll want to iterate over this list and show a power plant icon for each one:

coal
![sim-city-coal-plant](https://user-images.githubusercontent.com/919583/163299062-c4f8c382-5ee0-4ee6-b9e8-e05103096826.png)

gas
![sim-city-gas-plant](https://user-images.githubusercontent.com/919583/163299076-579d8c97-dc98-465a-b93a-392fab3f97f3.png)

oil
![sim-city-oil-plant](https://user-images.githubusercontent.com/919583/163299086-a56d8250-8d81-44a3-bdb4-50e83c330f82.png)

Each one should also show the power plant name, county, utility and MW capacity. This could be done either by hovering or displaying the text below it. The ultimate effect we want is something like what we have in the wireframes:

![Screen Shot 2022-04-13 at 9 01 33 PM](https://user-images.githubusercontent.com/919583/163299272-ada4ebc5-f9fa-464a-96b7-0aa1f0bcf870.png)

**Comment by derekeder** [comment]
@hkier want to take a stab at this one?

**Comment by hkier** [comment]
yes, thank you!

**Comment by hkier** [comment]
Crazy Passover/Easter weekend.  will work on it as I can.
