### ISSUE TITLE
Calculate And Show Emissions (MTCO2e) For Power Plants Rather Than Capacity

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#53]
In the [source data for power plants](https://docs.google.com/spreadsheets/d/17sBCD1prwzRsuA2oT-CA6VmOhEeB6Ao9m32B12EAPKs/edit#gid=737725675), each row has data on the emissions for each plant:

![Screen Shot 2022-04-15 at 4 59 57 PM](https://user-images.githubusercontent.com/919583/163640230-bfe20914-7ef0-410c-a4e4-22c0f25b6ce4.png)

It looks like these are broken out into individual types of emissions in the spreadsheet:

* CO2: `Plant unadjusted annual CO2 emissions (tons)`
* NOx (nitrogen oxide): `Plant unadjusted annual NOx emissions (tons)`
* SO2 (sulfur dioxide): `Plant unadjusted annual SO2 emissions (tons)`
* PM2.5 (particulate matter - is this a contributor to climate change or just bad for the local area?): `PM 2.5 Emssions (tons)`

If we import these rows, we could do a calculation of CO2 equivalent for each so we can show a single number for emissions for each plant. Can someone point us to the calculation to convert these numbers to CO2 equivalent?

Related to #49 #52 #23

**Comment by vkoves** [comment]
I actually wonder if we need to do this - although a 3,000 MW nuclear/gas combo plant may indeed not emit as much as a 2,000 MW gas only plant, the nuances of that seem a little too in the weeds for our site, and this hasn't been something I have heard.

**During tonight's breakout** - see if people agree that we should do this or think it's fine to skip.

**Comment by vkoves** [comment]
Closing this as part of #184, which may end up requiring this feature get added
