### ISSUE TITLE
Flesh Out the About Page

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#55]
We should flesh out the about page explaining generally:

- Who made this
- Why we made it
- Our sources?

**Comment by derekeder** [comment]
stubbed out a Google doc to draft content here: https://docs.google.com/document/d/1qXuioHvuRF28oBrKD_iPPiQRbiQw_A4kx3FU245e3go/edit#

**Comment by derekeder** [comment]
First draft of the about page is done. Open question on how we want to handle the data section

**Comment by vkoves** [comment]
@derekeder - should we rename the site to "Decarbonize My State"? It's a much shorter and catchier title in my mind than "What does it take to decarbonize my state".

**Comment by derekeder** [comment]
@jpvelez to take a pass on the copy here: https://docs.google.com/document/d/1qXuioHvuRF28oBrKD_iPPiQRbiQw_A4kx3FU245e3go/edit#

**Comment by hkier** [comment]
I have taken a look at the page on Google Docs.   I have made some quick edits and left comments in the document for other issues.  We should discuss this on Tuesday.
