### ISSUE TITLE
Flesh out the Terminology Page

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#56]
Explain any confusing terms, like CO2 equivalent, million metric tons, MW (Megawatts) capacity, and any other terms folks want to define.

**Comment by derekeder** [comment]
drafted a document here: https://docs.google.com/document/d/1VAIS0-47qUc7w6G9zJgXgY8BgmSWe-hJZGe6lRkI6GM/edit

**Comment by hkier** [comment]
I have added a bunch of terms and definitions to the terminology page.  Please take a look and let me know if I've missed any obvious terms which should be included on this page.

**Comment by vkoves** [comment]
@hkier - the doc looks like a great starting point! I think you can move to making this a PR and then we can move any language discussion into that PR

**Comment by vkoves** [comment]
Howard confirmed he can take on making the page, there is already a `terminology.js` so you should be able to flesh that out and then add headers.
