### ISSUE TITLE
Create & Add Final Graphics for Appliances & Power Plants

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#57]
We will need a set of graphics for home appliances, buildings, power plants, cars, etc that are consistent throughout the site. We'll need to find a graphic designer / illustrator to help us make these.

**Comment by hkier** [comment]
I think I found somebody to take this on.  I will give you folks more info in the Slack channel.

**Comment by derekeder** [comment]
Description of what we need:

We are looking for a graphic artist to create a set of static images we can use throughout our website that focus on power generation and building electrification. The website wireframes represent most of what we need: https://app.moqups.com/pcSQvUMmsyAa1SN58KaKg1EKuYRs8iRX/view/page/a97a1436c

Here's the full list of graphics we'll need:
* gas furnace, gas stove, gas hot water heater
* electric heat pump, induction stove, electric water heater
* car with exhaust coming out
* electric car
* coal, oil and gas power plants
* wind turbine, solar power plant

We're inspired by the retro/pixelated art from Sim City 2000, which we think do a good job on representing the various power sources, but it would be nice to have consistency between those and the rest of our graphics. Pixel art may be a good option to pursue as it fits within this theme.

![sim city sprites](https://user-images.githubusercontent.com/919583/165386890-986ce300-b484-48f3-835f-83e0a9414702.png)

**Comment by derekeder** [comment]
After discussing, we decided that our graphic needs are pretty specific - we like the power plants sim city style so it makes sense to get graphics for the appliances, cars, etc that match that style. This means finding a graphics artist that does pixel art.

@nofurtherinformation suggested we can find what we want on Fiverr: https://www.fiverr.com/search/gigs?query=pixel%20art&source=top-bar&acmpl=1&search_in=everywhere&search-autocomplete-original-term=pixel%20&search-autocomplete-available=true&search-autocomplete-type=suggest&search-autocomplete-position=1

**Comment by vkoves** [comment]
Derek mentioned he's going to have some art for us thanks to Juan Pablo's talk getting a video

**Comment by derekeder** [comment]
@jpvelez has a graphic artist working on a video related to this project. our plan is to reuse the same graphics here when they're ready.

**Comment by vkoves** [comment]
Closing this, Derek said we don't have the budget to get the mini power plant icons, and the current assets we have don't work. Plus folks online like the SimCity icons 🤷🏻‍♂️
