### ISSUE TITLE
Draft Call to Action Page

### ISSUE THREAD

**Issue by vkoves** [chihacknight/decarbonize-my-state#65]
This could go to a new Take Action page and then sections within it. This should fix all links in this type of panel:

![Screenshot from 2022-04-26 20-50-54](https://user-images.githubusercontent.com/3187531/165422260-01a6c236-7766-4976-97fb-551d6c9a1015.png)

**Comment by derekeder** [comment]
This website on Legal Pathways to Deep Decarbonization has a bunch of model legislation. https://lpdd.org/model-laws/

They also track laws passed in each state, which can be linked to directly with the state abbreviation code: https://lpdd.org/resources/?fwp_res_location=il

**Comment by derekeder** [comment]
@jmadans is going to do some research on this

**Comment by jmadans** [comment]
@jmadans is logging on.....

Initial impression is that we have decision to make: do we want people to better understand "what's happening" with regard to climate action in their state or do we want to connect with an advocacy group that is going to onboard them. If it's the latter than these trackers aren't going to solve that problem.

**Comment by derekeder** [comment]
Lets move this content into a 'Take action' page and link off to it. @jmadans would you mind taking a first draft of it in a Google doc with the research you've done?

**Comment by derekeder** [comment]
@jmadans has a draft of this page here: https://docs.google.com/document/d/1twZfl9xP096fnwq4TwkcXwEbNZKPNB7rWc4fsVMKWgk/edit

**Comment by jmadans** [comment]
Question for discussion: How will people get to the take action page? I think we should go with some combo of the following: 

1. Add it to the navigation in the top right (which currently just has home). Downside:  
2. Add it as another button to the right of "Back to Map" in each of the state profile pages. 
3. Pick a place on each of the state profile page to highlight the call to action. 
4. Pick multiple places to highlight the call to action page.
5. Have it pop up as a full width band that sticks to the page.

**Comment by vkoves** [comment]
Personally I'd suggest number 1 and number 3 and put the call to action at the bottom of the page, since we didn't want to break up the story of each state detail page.

**Comment by jmadans** [comment]
Here's a link to the draft google form: https://docs.google.com/forms/d/1423PcQc6klSW0osK_pmnsDEwrlvWoD6BcSRInu7p5I0/edit

I've made it editable by anyone with the link for now so you can edit the iframe code to make it fit however you want.

Here's the iframe code: 
`<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdiwiT6OZO0jsnLu22r6ClBZLh8fvfGIiYu_5coOvjYXqogtw/viewform?embedded=true" width="640" height="720" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>`
