### ISSUE TITLE
Add progress bar to electrical generation section

### ISSUE THREAD

**Issue by jpvelez** [chihacknight/decarbonize-my-state#68]
We should add progress bars to the electrical generation section:

"Coal plants closed"

or 

"Dirty Power Plants replaced with Clean Power Plants"

ectc

**Comment by derekeder** [comment]
A few challenges with showing "XX/145 power plants replaced":

- all power plants are not the same in terms of megawatts generated. is closing the biggest coal plant the same as closing the smallest gas plant? I would argue no
- we have no data on the history of closed coal plants. all the data we have is about the current state of things. it may not be possible to get an accurate count for all 50 states. Unless we just start at zero now and commit to tracking the closure of every power plant? Seems kind of arbitrary

I think the chart in @jpvelez's talk showing power broken down by emissions / renewables is pretty simple to grasp and we have the data for it already:
![Screen Shot 2022-04-29 at 10 45 36 AM](https://user-images.githubusercontent.com/919583/165981136-3daf555d-3c39-4835-9cdd-2de55ade59cc.png)

**Comment by jpvelez** [comment]
OK YOU WIN

for now

**Comment by vkoves** [comment]
Unless I'm confused, we have this:

![Screenshot from 2022-08-02 19-27-12](https://user-images.githubusercontent.com/3187531/182498916-64e82ccf-a7b3-4fda-8ad5-8d22633d6a93.png)

Closing this issue.
