### ISSUE TITLE
react-scrollspy is a dependancy

### ISSUE THREAD

**Issue by hkier** [chihacknight/decarbonize-my-state#70]
react-scrollspy is a dependency which is needed for an initial installation of the repository.  docker-compose up --build will fail because the dependency has not been added.  The user needs to manually add react-scrollspy.  Please update either the README document to indicated this needs to be manually added or update the package to automatically bring in this package.

**Comment by vkoves** [comment]
@derekeder - do you know anything about this? I added the dependency using the directions in the `README` but I also encountered issues with Docker not handling things.

**Comment by derekeder** [comment]
we discussed and it may be because `package-lock.json`, which should not be necessary anymore. I'll try removing this file to see if this resolves the issue
