### ISSUE TITLE
round emissions data to two decimal points

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#72]
In #71 @hkier rounded the projected emissions to two decimal points. We need to do the same for the historical emissions. This looks to be done here: https://github.com/chihacknight/decarbonize-my-state/blob/main/src/components/simpleareachart.js#L18

Looks like this:

![Screen Shot 2022-05-03 at 8 49 22 PM](https://user-images.githubusercontent.com/919583/166613252-b05f6fd7-70b1-407f-acd3-26f296cf8e6c.png)

**Comment by hkier** [comment]
@derekeder I created branch round-emissions for this issue and updated rounding in simpleareachart to 2 decimals.  However, the data coming in from emissions.json is only 1 decimal place.  The data extraction queries also need to be updated to 2 decimals.  However, I am not familiar with Python and would some assistance to update the data queries to provide the data with 2 decimal places.

**Comment by derekeder** [comment]
lets take a look at this tonight @hkier

**Comment by nofurtherinformation** [comment]
I'll be there tonight and can help take a look!
