### ISSUE TITLE
safari browser testing

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#93]
test the website using the Safari web browser and confirm that:

* Scrolling is easy
* Nav bar works
* Hoverable things are tappable
* Charts and maps look ok

**Comment by SuragNuthulapaty** [comment]
![Screen Shot 2022-05-17 at 8 17 17 PM](https://user-images.githubusercontent.com/77648585/168937516-e11ae74a-eadc-4190-8965-bd6cc7424e9c.png)
![Screen Shot 2022-05-17 at 8 17 31 PM](https://user-images.githubusercontent.com/77648585/168937514-86fba5a8-cd03-4a02-941d-cdd5d4458de7.png)

The site works as expected on safari
