### ISSUE TITLE
Create Sharing Social Images for Each State

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#97]
Using Canva.com, make some Twitter and Facebook cards from the site for visitors to share out.

Examples: https://justicedivided.com/action

Points to cover:
- national breakdown chart of emissions sources
- state map
- emissions breakdown for each state

**Comment by vkoves** [comment]
Here's the comment I made on another issue:

https://github.com/chihacknight/decarbonize-my-state/issues/96#issuecomment-1134005902

**Comment by vkoves** [comment]
@shriyash - are you still taking this on? This would be a nice upgrade and make sharing our site more compelling, as right now folks generally screenshot that graph when sharing the site out on social media if they are sharing a state page

**Comment by vkoves** [comment]
Reassigned to Surag since we haven't seen Shri in the group in a while.

**Comment by nofurtherinformation** [comment]
Note - the puppeteer code should likely happen in the `gastby-node` script: https://github.com/chihacknight/decarbonize-my-state/blob/main/gatsby-node.js

**Comment by vkoves** [comment]
Surag did that! It works. Proof:
